Damans227/adding map
MLH-Fellowship/pod-4.1.5-portfolio pull request #15
Opened 2021-11-09 23:46 UTC by Damans227

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

This pull request is a work in progress to add the following enhancement: https://github.com/MLH-Fellowship/pod-4.1.5-portfolio/issues/10

Test server: [add-map-prep-pod-4-1-5.netlify.app](https://add-map-prep-pod-4-1-5.netlify.app/)

Resources leveraged to build the custom map: 

1) [Leaflet](https://leafletjs.com/)
2) [Tutorial](https://www.youtube.com/watch?v=nZaZ2dB6pow)

2021-11-09 23:47 UTC, Damans227 commented
@Shikhar15606 @khattakdev Ptal, thx!

2021-11-10 15:10 UTC, khattakdev commented
@Damans227 Always add someone as a reviewer to check and review your code.

2021-11-10 15:10 UTC, Damans227 commented
> @Damans227 Always add someone as a reviewer to check and review your code.

Ok.

2021-11-10 18:48 UTC, P0intMaN approved these changes
LGTM! As far this PR is concerned, it doesn't deal with the 'pop-up card feature' right? 

By pop-up card feature, I mean when a user clicks on the profile, a card would pop up displaying the basic info (role, country).

2021-11-10 18:50 UTC, P0intMaN commented
I mean, that can be a part of another PR. This PR satisfies the purpose it was created for, Awesome work @Damans227 @Shikhar15606

2021-11-10 18:52 UTC, Damans227 commented
> LGTM! As far this PR is concerned, it doesn't deal with the 'pop-up card feature' right? 
> 
> By pop-up card feature, I mean when a user clicks on the profile, a card would pop up displaying the basic info (role, country).

Yea, it's only half baked is what I would say. Adding user details and possibly making it a pop up card is what we are aiming to work on as next steps in this PR.

2021-11-10 18:52 UTC, Damans227 commented
> That can be a part of another PR though. This PR satisfies the purpose it was created for, Awesome work @Damans227 @Shikhar15606 

Much thx!

2021-11-10 20:01 UTC, Shikhar15606 requested changes
Great Work @Damans227. We will need to make a few changes.

2021-11-10 21:55 UTC, Shikhar15606 commented on _sass/map.scss
> +  width: 800px;
Fixed it

2021-11-10 21:55 UTC, Shikhar15606 commented on assets/js/marker.js
> +    L.marker([45.4214, -75.6901], { icon: markerIcon }).addTo(map);
Fixed it

2021-11-10 21:55 UTC, Shikhar15606 commented on _includes/podmap.html
> +<div class="map-container">
Fixed it

2021-11-10 22:30 UTC, Damans227 commented on _includes/header.html
> +  <!-- Required meta tags -->
Thanks for the feedback.

2021-11-10 22:30 UTC, Damans227 commented on _includes/header.html
> +  <script
Yup, I will remember switching prettier off next time.

2021-11-10 22:30 UTC, Damans227 commented on _includes/header.html
> +  <!-- Leaflet CSS and Script-->
Totally!

2021-11-10 22:30 UTC, Damans227 commented on _includes/podmap.html
> +<div class="map-container">
Thanks Shikhar!

2021-11-11 13:15 UTC, khattakdev commented
should I merge this PR @P0intMaN @Shikhar15606 ?

2021-11-11 13:25 UTC, esh04 approved these changes
Looks good to me!

2021-11-11 13:42 UTC, khattakdev approved these changes

2021-11-11 13:42 UTC, merged